football_love/src/main/java/com/deu/football_love/domain/Address.java
football_love/src/main/java/com/deu/football_love/domain/Board.java
football_love/src/main/java/com/deu/football_love/domain/Company.java
football_love/src/main/java/com/deu/football_love/domain/MatchTeam.java
football_love/src/main/java/com/deu/football_love/domain/Matches.java
football_love/src/main/java/com/deu/football_love/domain/Member.java
football_love/src/main/java/com/deu/football_love/domain/Post.java
football_love/src/main/java/com/deu/football_love/domain/Stadium.java
football_love/src/main/java/com/deu/football_love/domain/StadiumImage.java
football_love/src/main/java/com/deu/football_love/domain/Team.java

jpa 매핑을 위한 domain 추가
- jpa 매핑을 위해 domain을 추가했습니다.
- 
-

[feat]domain 추가

---

football_love/build.gradle
football_love/src/main/java/com/deu/football_love/FootballLoveApplication.java
football_love/src/main/java/com/deu/football_love/config/WebSecurityConfig.java
football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java
football_love/src/test/java/com/deu/football_love/membertest/MemberTest.java

- spring security 적용
- 로그인 api 작성
- 회원가입 api 작성
-

로그인 회원가입 api작성, 중복확인 api 미완성, 비밀번호 암호화 적용

---

football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/domain/ParticipationMember.java
football_love/src/main/java/com/deu/football_love/domain/Post.java
football_love/src/main/java/com/deu/football_love/domain/WithdrawalMember.java
football_love/src/main/java/com/deu/football_love/domain/type/MemberType.java
football_love/src/main/java/com/deu/football_love/dto/BoardDto.java
football_love/src/main/java/com/deu/football_love/dto/MemberDto.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/repository/sql/MemberSql.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java

- 쿼리문 MemberSql클래스로 분리
- 멤버권한 확인 API 작성
- 회원탈퇴 API 작성
-

[feat] member API 완성 및 쿼리문 MemberSql클래스로 분리

---

front/src/Carousel.jsx
front/src/index.css
front/src/slider.js

- 이미지슬라이더완성
- 특이 사항 1
- 특이 사항 2

[feat]slider완성

---

football_love/src/main/java/com/deu/football_love/controller/PostController.java
football_love/src/main/java/com/deu/football_love/controller/TeamController.java
football_love/src/main/java/com/deu/football_love/domain/ApplicationJoinTeam.java
football_love/src/main/java/com/deu/football_love/domain/Member.java
football_love/src/main/java/com/deu/football_love/domain/Post.java
football_love/src/main/java/com/deu/football_love/domain/Team.java
football_love/src/main/java/com/deu/football_love/domain/TeamMember.java
football_love/src/main/java/com/deu/football_love/dto/AcceptApplicationResponse.java
football_love/src/main/java/com/deu/football_love/dto/ApplicationJoinTeamDto.java
football_love/src/main/java/com/deu/football_love/dto/CreateTeamResponse.java
football_love/src/main/java/com/deu/football_love/dto/DeletePostResponse.java
football_love/src/main/java/com/deu/football_love/dto/DisbandmentTeamResponse.java
football_love/src/main/java/com/deu/football_love/dto/MemberDto.java
football_love/src/main/java/com/deu/football_love/dto/ModifyPostResponse.java
football_love/src/main/java/com/deu/football_love/dto/PostDto.java
football_love/src/main/java/com/deu/football_love/dto/TeamDto.java
football_love/src/main/java/com/deu/football_love/dto/TeamMemberDto.java
football_love/src/main/java/com/deu/football_love/dto/UpdateAuthorityResponse.java
football_love/src/main/java/com/deu/football_love/dto/WritePostRequest.java
football_love/src/main/java/com/deu/football_love/service/PostService.java
football_love/src/main/java/com/deu/football_love/service/PostServiceImpl.java
football_love/src/main/java/com/deu/football_love/service/TeamService.java
football_love/src/main/java/com/deu/football_love/service/TeamServiceImpl.java
football_love/src/test/java/com/deu/football_love/membertest/MemberTest.java
football_love/src/test/java/com/deu/football_love/service/TeamServiceImplTest.java

- Service에서 Controller 간의 데이터를 DTO로 주고받기 때문에 team, post 부분 수정
- DTO 사용에 따른 테스트 코드 수정
- MemberDTO에서 탈퇴 정보의 null 예외처리가 안되어있어 임시 수정
- cascade 옵션 수정
- 그 외 refactoring
- Member 부분에 약간의 수정이 있었습니다. 확인해주세요

[feat][fix][refactor] team, post 파트 수정

---

front/src/Carousel.jsx
front/src/MainContainer.jsx
front/src/index.css
front/src/slider.js

- 슬라이드 오류해결 (슬라이드가 자동으로 넘어가는 속도가 점점 빨라지는 오류 해결)
- 요일,날짜 버튼 만듦
- 특이 사항 1
- 특이 사항 2

[fix]슬라이드 오류해결

---

front/src/Carousel.jsx
front/src/MainContainer.jsx
front/src/utils.js

- Date Slider 구현중
- 특이 사항 1
- 특이 사항 2

[feat]Date Slider 구현중

---

football_love/src/main/java/com/deu/football_love/controller/PostController.java
football_love/src/main/java/com/deu/football_love/controller/TeamController.java
football_love/src/main/java/com/deu/football_love/domain/ApplicationJoinTeam.java
football_love/src/main/java/com/deu/football_love/domain/Company.java
football_love/src/main/java/com/deu/football_love/domain/Member.java
football_love/src/main/java/com/deu/football_love/domain/ParticipationMember.java
football_love/src/main/java/com/deu/football_love/domain/Post.java
football_love/src/main/java/com/deu/football_love/domain/TeamMember.java
football_love/src/main/java/com/deu/football_love/domain/WithdrawalMember.java
football_love/src/main/java/com/deu/football_love/domain/type/MemberType.java
football_love/src/main/java/com/deu/football_love/dto/AddCompanyResponse.java
football_love/src/main/java/com/deu/football_love/dto/CompanyDto.java
football_love/src/main/java/com/deu/football_love/dto/JoinRequest.java
football_love/src/main/java/com/deu/football_love/dto/MemberResponse.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/repository/TeamRepository.java
football_love/src/main/java/com/deu/football_love/repository/TeamRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/service/CompanyService.java
football_love/src/main/java/com/deu/football_love/service/CompanyServiceImpl.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java
football_love/src/main/java/com/deu/football_love/service/PostServiceImpl.java
football_love/src/main/java/com/deu/football_love/service/TeamService.java
football_love/src/main/java/com/deu/football_love/service/TeamServiceImpl.java
football_love/src/test/java/com/deu/football_love/service/CompanyServiceTest.java
football_love/src/test/java/com/deu/football_love/service/StadiumServiceTest.java
football_love/src/test/java/com/deu/football_love/service/TeamServiceImplTest.java

- Memer Entity의 PK를 member_Id에서 member_number로 변경했습니다.
- 그에따른 repository, service, controller 전체에 걸친 수정을 했습니다.
- Member DTO 부분에 memberNumber를 추가했습니다.
- 다른 Entity와의 매핑 정보를 수정 했습니다.
- Member Type 필드를 추가했습니다.
- 위 변경 사항에 따른 테스트 코드 수정 했습니다.
- conflict 주의
- teamMemberDto도 memberNumber고려해서 수정해야할듯

2021-11-22 작업내역

---

front/src/MainContainer/DateCarousel.jsx
front/src/MainContainer/Filter.jsx
front/src/MainContainer/MainContainer.jsx

[feat]Region Bar

---

front/package-lock.json
front/package.json
front/src/App.js
front/src/MainContainer/DateCarousel.jsx
front/src/assets/leftArrow.svg
front/src/assets/rightArrow.svg
front/src/index.css
front/yarn.lock

- Date Carousel(Slider) ArrowImg Add ( With Color Change { Blue , Gray } )

[feat]Carousel ArrowImage Add

---

front/src/MainContainer/DateCarousel.jsx
front/src/MainContainer/DeadlineFilter.jsx
front/src/MainContainer/Filter.jsx
front/src/MainContainer/Temp.js

- Filter 구현 완료
- 특이 사항 1
- 특이 사항 2

[Feat]Filter구현 완료

---

front/src/AuthComponents/Div1items.jsx
front/src/AuthComponents/JoinModal.jsx
front/src/AuthComponents/JoinPage.jsx
front/src/AuthComponents/MainDiv.jsx
front/src/AuthComponents/SubBar.jsx
front/src/MainContainer/DateCarousel.jsx
front/src/Navbar.jsx
front/src/index.css

- 작업 내역 1
- 작업 내역 2
- 작업 내역 3
- 작업 내역 4
- 특이 사항 1
- 특이 사항 2

[feat]회원가입페이지 구현중

---

football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/repository/sql/MemberSql.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java
football_love/src/test/java/com/deu/football_love/member/MemberTest.java

- 기존 로그인방식 삭제
- 멤버 쿼리 jpql쿼리로 변경
-

[fix] 기존 로그인방식 삭제 및 쿼리 jpql로 변경

---

football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/dto/auth/ValidRefreshTokenResponse.java

- 오타로 인한 refresh api가 정상 작동되지 않던것을 수정했습니다.
.

[fix]refresh Api 작동안되던 것 수정

---

football_love/src/main/java/com/deu/football_love/controller/BoardController.java
football_love/src/main/java/com/deu/football_love/controller/PostController.java
football_love/src/main/java/com/deu/football_love/dto/board/DeleteBoardResponse.java
football_love/src/main/java/com/deu/football_love/dto/post/DeletePostRequest.java
football_love/src/main/java/com/deu/football_love/dto/post/DeletePostResponse.java
football_love/src/main/java/com/deu/football_love/service/BoardService.java
football_love/src/main/java/com/deu/football_love/service/BoardServiceImpl.java
football_love/src/test/java/com/deu/football_love/member/MemberSecurityTest.java

- board와 post 파트를 수정했습니다.
- teamName -> teamId
- SpringSecurity 적용한것에 따른 변경
- Unauthorized -> Forbidden
- 등 로직 정리

[fix] board, post 부분 수정

---

football_love/src/main/java/com/deu/football_love/controller/MatchController.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java

- AuthorityType -> TeamMemberType, 
- login 삭제 (jwt 사용)

[fix]AuthorityType -> TeamMemberType, login 삭제

---

football_love/src/main/java/com/deu/football_love/controller/MatchController.java
football_love/src/main/java/com/deu/football_love/dto/match/MatchApplicationResponse.java
football_love/src/main/java/com/deu/football_love/dto/match/MatchApproveResponse.java
football_love/src/main/java/com/deu/football_love/service/MatchService.java
football_love/src/main/java/com/deu/football_love/service/MatchServiceImpl.java
football_love/src/test/java/com/deu/football_love/service/MatchTest.java

- Match 테스트코드 작성
- MatchApplicationResponse,MatchApproveResponse Dto클래스 추가
-

[feat] Match 테스트코드 작성 및 DTO 추가

---

front/src/App.js
front/src/components/Avatar.jsx
front/src/components/Login/Login.jsx
front/src/components/MainContainer/Carousel.jsx
front/src/components/MainContainer/DateCarousel.jsx
front/src/components/Navbar.jsx

- 로그인 완료시 Navbar contents 바뀜
- Avatar 컴포넌트 추가
- 작동 여부 테스트해야됨.

[feat]로그인시 Navbar 바뀜 & Avatar 컴포넌트 추가

---

football_love/src/main/java/com/deu/football_love/config/WebSecurityConfig.java
football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/dto/auth/LoginResponse.java
football_love/src/main/java/com/deu/football_love/dto/company/QueryCompanyDto.java
football_love/src/main/java/com/deu/football_love/dto/member/MemberJoinRequest.java
football_love/src/main/java/com/deu/football_love/dto/member/QueryMemberDto.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java

- 멤버 정보 조회 api를 추가 했습니다.
- 멤버 key를 로그인시 반환합니다 memberNumber
- json으로 전달 시 birth는 yyyyMMdd 형식으로 전달하도록 지정했습니다.

멤버 정보조회 api 추가, birth 형식 지정

---

football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepositoryImpl.java
football_love/src/main/java/com/deu/football_love/repository/sql/MemberSql.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java

- selectMemberAuthority 관련 함수 수정했습니다. 쿼리 등.
- fetch join을 활용하고 TeamMemberType으로 반환을 하도록 했습니다.

[fix]selectMemberAuthority 쿼리 안되는 것 수정

---

front/src/App.js
front/src/axios/axios.js
front/src/components/CheckLogin.jsx
front/src/components/ErrorPage/LoginPlz.jsx
front/src/components/Join/Join.jsx
front/src/components/Profile/Profile.jsx
front/src/components/Profile/ProfileContainer.jsx
front/src/components/Write/Write.jsx
front/src/components/Write/WriteContainer.jsx

- 로그인 확인 로직
- 글작성 컴포넌트 생성
- 특이 사항 1
- 특이 사항 2

[feat]로그인 확인로직 리펙토링 및 글작성컴포넌트 생성

---

football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/domain/Member.java
football_love/src/main/java/com/deu/football_love/dto/member/UpdateMemberRequest.java
football_love/src/main/java/com/deu/football_love/service/MemberServiceImpl.java
football_love/src/test/java/com/deu/football_love/controller/MemberControllerTest.java
football_love/src/test/java/com/deu/football_love/member/MemberTest.java

- UpdateMemberRequest 불필요한 멤버변수 제거 및 빌더패턴 적용,생성자 접근 범위 제한
- 회원정보 수정,회원탈퇴 요청 컨트롤러 테스트 추가, 자주 테스트에 사용되는 객체 상수로 선언
- 회원정보 수정의 매개변수에@AuthenticationPrincipal 어노테이션 적용(로그인 정보)
-

[feat] 테스트코드 작성 및 리팩토링

---

football_love/src/main/java/com/deu/football_love/config/JwtAuthenticationFilter.java
football_love/src/main/java/com/deu/football_love/config/WebSecurityConfig.java
football_love/src/main/java/com/deu/football_love/controller/MemberController.java
football_love/src/main/java/com/deu/football_love/controller/TeamController.java
football_love/src/main/java/com/deu/football_love/domain/Team.java
football_love/src/main/java/com/deu/football_love/dto/team/QueryTeamListItemDto.java
football_love/src/main/java/com/deu/football_love/repository/MemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/TeamMemberRepository.java
football_love/src/main/java/com/deu/football_love/repository/TeamRepository.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java
football_love/src/main/java/com/deu/football_love/service/TeamService.java
football_love/src/test/java/com/deu/football_love/service/TeamServiceTest.java

- 로그아웃이 안되던 문제 해결했습니다.
- 로그아웃 됐을 시 LoginInfo가 초기화 되지 않는 문제였습니다.
- 그 외 유저정보 로드 시 문제가 발생했던 것들 수정했습니다.
- 로그인한 유저의 소속 팀 조회 API를 추가했습니다.

[fix] 로그아웃 문제 해결, [feat] 나의 소속 팀 정보 조회 API 추가

---

football_love/src/main/java/com/deu/football_love/dto/member/QueryMemberDto.java
football_love/src/main/java/com/deu/football_love/service/MemberService.java

- QueryMemberDto team정보 제거
- QueryMemberDto 미사용 멤버변수 participationMembers 제거
-

QueryMemberDto team정보 제거 및 미사용 멤버변수 제거

---

football_love/src/main/java/com/deu/football_love/controller/TeamController.java
football_love/src/main/java/com/deu/football_love/dto/team/JoinApplyRequest.java
football_love/src/test/java/com/deu/football_love/controller/TeamControllerTest.java

- TeamController 테스트코드 작성
- JoinApplyRequest 생성자 추가
- JoinApplyRequest 멤버변수 첫글자 소문자로 변경(첫글자 대문자시 Jackson라이브러리에서 json변환이 동작하지 않음)
- team Api url 오타 수정
-

TeamControllerTest

---

front/src/axios/axios.js
front/src/components/NavBar/MenuList.tsx
front/src/components/TeamPage/TeamPage.tsx
front/src/components/TeamPage/TeamPageInfo.tsx

[feat]axios 리턴값 테스트

---

front/src/components/Join/Join.tsx
front/src/components/Login/Login.tsx

- Add business user checkbox when sign up.

add business sign up

---

football_love/src/main/java/com/deu/football_love/FootballLoveApplication.java

git hub hook과 jenkins를 사용해서 master 브랜치에 변동사항이 발생 시 배포 서버에 자동으로 빌드하고 서버를 실행하는 테스트를 진행합니다.
- [x\  PR과 관련없는 변경사항이 없는가?
- [x\ 내 코드에 대한 자기 검토가 되었는가?

[test]자동 배포 테스트

---

front/src/App.tsx
front/src/components/Join/Join.tsx
front/src/components/NavBar/MenuList.tsx
front/src/components/community/CategoryHeader.tsx
front/src/components/community/Community.tsx
front/src/components/community/PageButton.tsx
front/src/components/community/PostRow.tsx
front/src/components/community/PostWrapper.tsx
front/src/components/community/WriteButton.tsx

- 전체 보드 페이지 생성 (static mock-up version)

전체 보드 페이지 생성(static mock-up)

---

football_love/src/main/java/com/deu/football_love/FootballLoveApplication.java
football_love/src/main/java/com/deu/football_love/config/SwaggerConfig.java
football_love/src/main/java/com/deu/football_love/controller/BoardController.java
football_love/src/main/java/com/deu/football_love/dto/board/QueryBoardDto.java
football_love/src/main/java/com/deu/football_love/dto/team/QueryTeamDto.java
football_love/src/main/java/com/deu/football_love/repository/BoardRepository.java
football_love/src/main/java/com/deu/football_love/service/BoardService.java
football_love/src/test/java/com/deu/football_love/controller/BoardControllerTest.java
football_love/src/test/java/com/deu/football_love/controller/MemberControllerTest.java
football_love/src/test/java/com/deu/football_love/service/BoardServiceTest.java

- BoardDto 클래스명 QueryBoardDto로 수정
- 서버 실행시 notice게시판 추가하도록 코드 작성
- existsCommonBoardByBoardName 쿼리 수정
- Swagger 임시 수정
-

Board Get  API 작성 및 서버 실행시 게시판 하나 추가하도록 변경

---

front/src/axios/axios.js
front/src/components/Admin/AdminPage.tsx
front/src/components/community/Community.tsx

- community Component 리펙토링
- 기존 정적인 상태에서 state 를 사용하는 동적인 상태로 변경

refactoring communityComponent
